import json

PREV = "/home/user/homeassistant-remotecompose/previews/build/compose-previews/renders"
APP = "/home/user/homeassistant-remotecompose/app/build/compose-previews/renders"

def screen(name): return f"{APP}/{name}.png"
def prev(name): return f"{PREV}/{name}.png"

spec = {
  "title": "Terrazzo — Design Board",
  "tagline": "Rendered @Preview exports of the homeassistant-remotecompose (Terrazzo) app, "
             "staged for Claude Design. Category 1 covers the app surface + design system; "
             "Category 2 shows every widget/card class at app, Wear, and launcher-widget sizes. "
             "Every frame is a real Compose render (compose-preview skill), not a mock.",
  "palette": [
    {"name": "Home (HA blue)", "hex": "#03A9F4"},
    {"name": "Mushroom", "hex": "#E89F71"},
    {"name": "Minimalist", "hex": "#3F4A5C"},
    {"name": "Kiosk", "hex": "#00897B"},
    {"name": "Surface (dark)", "hex": "#0F1115"},
  ],
  "footer": "Generated by scripts/build-design-board.py from compose-preview renders. "
            "Self-contained: images inlined as base64. Drop into Claude Design, or open and use web capture.",
  "categories": [
    {
      "badge": "01 · App",
      "title": "App guide — screens, design system & dashboards",
      "intro": "The primary app surfaces a user moves through, the five theme styles that define the "
               "design system, and an intro to the data-driven dashboards.",
      "groups": [
        {
          "title": "Main screens",
          "note": "Phone @412×892dp. The flow: onboard → pick a dashboard → view it → manage widgets → "
                  "drill into history → settings.",
          "layout": "row",
          "items": [
            {"src": screen("Screen_Discovery_discovery"), "caption": "Discovery", "sub": "onboarding / first launch"},
            {"src": screen("Screen_DashboardView_dashboard_view"), "caption": "Dashboard view", "sub": "main home surface"},
            {"src": screen("Screen_DashboardPicker_dashboard_picker"), "caption": "Dashboard picker", "sub": "switch dashboards"},
            {"src": screen("Screen_Widgets_widgets"), "caption": "Widgets", "sub": "installed widget manager"},
            {"src": screen("Screen_CardHistory_card_history"), "caption": "Card history", "sub": "entity detail / history"},
            {"src": screen("Screen_ManagePinned_manage_pinned"), "caption": "Manage pinned", "sub": "pinned cards"},
            {"src": screen("Screen_Settings_settings"), "caption": "Settings", "sub": "app configuration"},
          ],
        },
        {
          "title": "Design system — theme styles",
          "note": "Five curated palettes + Material 3. Each is a materialkolor scheme derived from a single "
                  "seed (Home #03A9F4, Mushroom #E89F71, Minimalist #3F4A5C, Kiosk #00897B) paired with a "
                  "Google-Fonts typeface. Tokens live in rc-components/.../HaTheme.kt & TerrazzoTheme.kt. "
                  "Each tile shows key color roles, the surface-elevation strip, and two sample cards.",
          "layout": "grid",
          "items": [
            {"src": prev("Theme_Material3_Light_theme_Material3_light"), "caption": "Material 3", "sub": "light · dynamic color"},
            {"src": prev("Theme_Material3_Dark_theme_Material3_dark"), "caption": "Material 3", "sub": "dark"},
            {"src": prev("Theme_Home_Light_theme_Home_light"), "caption": "Home", "sub": "light · HA blue · Roboto Flex/Inter"},
            {"src": prev("Theme_Home_Dark_theme_Home_dark"), "caption": "Home", "sub": "dark"},
            {"src": prev("Theme_Mushroom_Light_theme_Mushroom_light"), "caption": "Mushroom", "sub": "light · salmon · Figtree"},
            {"src": prev("Theme_Mushroom_Dark_theme_Mushroom_dark"), "caption": "Mushroom", "sub": "dark"},
            {"src": prev("Theme_Minimalist_Light_theme_Minimalist_light"), "caption": "Minimalist", "sub": "light · slate · IBM Plex Sans"},
            {"src": prev("Theme_Minimalist_Dark_theme_Minimalist_dark"), "caption": "Minimalist", "sub": "dark"},
            {"src": prev("Theme_Kiosk_Light_theme_Kiosk_light"), "caption": "Kiosk", "sub": "light · teal · Atkinson Hyperlegible"},
            {"src": prev("Theme_Kiosk_Dark_theme_Kiosk_dark"), "caption": "Kiosk", "sub": "dark"},
          ],
        },
        {
          "title": "Dashboards — intro",
          "note": "Dashboards are vertical card stacks built from a Home Assistant config + state snapshot. "
                  "A representative spread of mobile layouts (@411dp wide); each also has a tablet variant.",
          "layout": "grid",
          "items": [
            {"src": prev("DashboardClimateMobile_dashboard_climate_mobile"), "caption": "Climate", "sub": "mobile"},
            {"src": prev("DashboardEnergyMobile_dashboard_energy_mobile"), "caption": "Energy", "sub": "mobile"},
            {"src": prev("DashboardSecurityMobile_dashboard_security_mobile"), "caption": "Security", "sub": "mobile"},
            {"src": prev("DashboardNetworksMobile_dashboard_networks_mobile"), "caption": "Networks", "sub": "mobile"},
            {"src": prev("Dashboard3dPrintingMobile_dashboard_3d_printing_mobile"), "caption": "3D printing", "sub": "mobile"},
            {"src": prev("DashboardGithubMobile_dashboard_github_mobile"), "caption": "GitHub", "sub": "mobile"},
          ],
        },
      ],
    },
    {
      "badge": "02 · Widgets",
      "title": "Widgets by size class",
      "intro": "One frame per widget/card class. Each render shows the same card across every surface it "
               "targets: App card (in-app width) · Wear S · Wear L · Widget smallest · mid · largest "
               "(launcher grid cells). This is the size-class matrix the app uses to pick a layout per surface.",
      "groups": [
        {"title": "Chips & single-entity", "note": "Small class — 1×1 to 2×2 launcher cells.", "layout": "wide", "items": [
            {"src": prev("CardPreviewMatrix_Tile_matrix_tile"), "caption": "Tile"},
            {"src": prev("CardPreviewMatrix_Entity_matrix_entity"), "caption": "Entity"},
            {"src": prev("CardPreviewMatrix_Button_matrix_button"), "caption": "Button"},
            {"src": prev("CardPreviewMatrix_Sensor_matrix_sensor"), "caption": "Sensor"},
            {"src": prev("CardPreviewMatrix_Statistic_matrix_statistic"), "caption": "Statistic"},
            {"src": prev("CardPreviewMatrix_Gauge_matrix_gauge"), "caption": "Gauge"},
        ]},
        {"title": "Arc-dial controls", "note": "Medium square class — 3×3 cells. Light / climate dials.", "layout": "wide", "items": [
            {"src": prev("CardPreviewMatrix_Light_matrix_light"), "caption": "Light"},
            {"src": prev("CardPreviewMatrix_Thermostat_matrix_thermostat"), "caption": "Thermostat"},
            {"src": prev("CardPreviewMatrix_Humidifier_matrix_humidifier"), "caption": "Humidifier"},
        ]},
        {"title": "Lists & multi-row", "note": "Tall / many-row class — 4×3+ cells.", "layout": "wide", "items": [
            {"src": prev("CardPreviewMatrix_Entities_matrix_entities"), "caption": "Entities"},
            {"src": prev("CardPreviewMatrix_TodoList_matrix_todo_list"), "caption": "To-do list"},
            {"src": prev("CardPreviewMatrix_Calendar_matrix_calendar"), "caption": "Calendar"},
            {"src": prev("CardPreviewMatrix_Logbook_matrix_logbook"), "caption": "Logbook"},
        ]},
        {"title": "Charts & time-series", "note": "Wide chart class — 3×2 cells.", "layout": "wide", "items": [
            {"src": prev("CardPreviewMatrix_HistoryGraph_matrix_history_graph"), "caption": "History graph"},
            {"src": prev("CardPreviewMatrix_WeatherForecast_matrix_weather_forecast"), "caption": "Weather forecast"},
            {"src": prev("CardPreviewMatrix_Markdown_matrix_markdown"), "caption": "Markdown"},
        ]},
        {"title": "Media, picture & panels", "note": "Hero / portrait-control classes — 4×2 to 4×5 cells.", "layout": "wide", "items": [
            {"src": prev("CardPreviewMatrix_MediaControl_matrix_media_control"), "caption": "Media control"},
            {"src": prev("CardPreviewMatrix_PictureEntity_matrix_picture_entity"), "caption": "Picture entity"},
            {"src": prev("CardPreviewMatrix_AlarmPanel_matrix_alarm_panel"), "caption": "Alarm panel"},
        ]},
      ],
    },
  ],
}

json.dump(spec, open("/tmp/board-spec.json", "w"), indent=2)
print("spec written")
